remove destroy and revert

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -161,8 +161,8 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
       # Here's where you will add some code to rollback on failure  
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - destroy-environment:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   configure-infrastructure:
     docker:
@@ -190,8 +190,8 @@ jobs:
             ansible-playbook -i inventory.txt configure-server.yml
           no_output_timeout: 30m
       # Here's where you will add some code to rollback on failure   
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - destroy-environment:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       
 
   run-migrations:
@@ -217,8 +217,8 @@ jobs:
                 curl --insecure https://kvdb.io/2dFzmoGD4AmGs53x9rUtmv/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
             if
       # Here's where you will add some code to rollback on failure   
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - destroy-environment:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   deploy-frontend:
     docker:
@@ -256,10 +256,10 @@ jobs:
             tar -czvf artifact "{CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
       # Here's where you will add some code to rollback on failure  
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - destroy-environment:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
                     
   deploy-backend:
     docker:
@@ -311,10 +311,10 @@ jobs:
             ansible-playbook -i inventory.txt deploy-backend.yml
             
       # Here's where you will add some code to rollback on failure  
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - destroy-environment:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   smoke-test:
     docker:
@@ -369,78 +369,78 @@ jobs:
               return 1
             fi
       # Here's where you will add some code to rollback on failure
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - destroy-environment:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
-  cloudfront-update:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            yum install tar gzip -y
-      - run:
-          name: Get old stack worflow id
-          command: |
-            export OldWorkflowID=$(aws cloudformation \
-              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-              --no-paginate --output text | grep -o '[^-]*$')
-            echo $OldWorkflowID >> ~/project/OldWorkflowID.txt
-            cat ~/project/OldWorkflowID.txt
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/OldworkflowID.txt
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-              -template-file .circleci/files/cloudfront.yml \
-              -stack-name initial-stack \
-              --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7} \
-              -tags project=udapeople
-            echo OldworkflowID: $(cat ~/project/OldWorkflowID.txt)
-            echo CurrentWorkflowID : "${CIRCLE_WORKFLOW_ID:0:7}"
-      # Here's where you will add some code to rollback on failure  
+  # cloudfront-update:
+  #   docker:
+  #     - image: amazon/aws-cli
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           yum install tar gzip -y
+  #     - run:
+  #         name: Get old stack worflow id
+  #         command: |
+  #           export OldWorkflowID=$(aws cloudformation \
+  #             list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+  #             --no-paginate --output text | grep -o '[^-]*$')
+  #           echo $OldWorkflowID >> ~/project/OldWorkflowID.txt
+  #           cat ~/project/OldWorkflowID.txt
+  #     - persist_to_workspace:
+  #         root: ~/
+  #         paths:
+  #           - project/OldworkflowID.txt
+  #     - run:
+  #         name: Update cloudfront distribution
+  #         command: |
+  #           aws cloudformation deploy \
+  #             -template-file .circleci/files/cloudfront.yml \
+  #             -stack-name initial-stack \
+  #             --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7} \
+  #             -tags project=udapeople
+  #           echo OldworkflowID: $(cat ~/project/OldWorkflowID.txt)
+  #           echo CurrentWorkflowID : "${CIRCLE_WORKFLOW_ID:0:7}"
+  #     # Here's where you will add some code to rollback on failure  
 
-  cleanup:
-      docker:
-        - image: amazon/aws-cli
-      steps:
-        - checkout
-        - run:
-            name: Install dependencies
-            command: |
-              ym install tar gzip -y
-        - attach_workspace:
-            at: ~/
-        - run:
-            name: Get old stack workflow id
-            command: |
-              export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-                --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-              echo Stack names: "${STACKS[@]}"
-              cat ~/project/OldWorkflowID.txt
-              export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
-              echo OldworkflowID: "${OldWorkflowID}"
-        - run:
-            name: Remove old stacks and files
-            command: |
-              export OldWorkflowID=$(cat ~/pdoject/OldWorkflowID.txt)
-              if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${oldWorkflowID}" ]]
-              then
-                echo "Deleting old stack"
-                echo "s3://udapeople-${OldWorkflowID}"
-                aws s3 rm "s3://udapeople-S{OldWorkflowID}" --recursive || true
-                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" || true
-                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" || true
-              else
-                echo "Stack is the latest"
-              fi
+  # cleanup:
+  #     docker:
+  #       - image: amazon/aws-cli
+  #     steps:
+  #       - checkout
+  #       - run:
+  #           name: Install dependencies
+  #           command: |
+  #             ym install tar gzip -y
+  #       - attach_workspace:
+  #           at: ~/
+  #       - run:
+  #           name: Get old stack workflow id
+  #           command: |
+  #             export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+  #               --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+  #             echo Stack names: "${STACKS[@]}"
+  #             cat ~/project/OldWorkflowID.txt
+  #             export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+  #             echo OldworkflowID: "${OldWorkflowID}"
+  #       - run:
+  #           name: Remove old stacks and files
+  #           command: |
+  #             export OldWorkflowID=$(cat ~/pdoject/OldWorkflowID.txt)
+  #             if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${oldWorkflowID}" ]]
+  #             then
+  #               echo "Deleting old stack"
+  #               echo "s3://udapeople-${OldWorkflowID}"
+  #               aws s3 rm "s3://udapeople-S{OldWorkflowID}" --recursive || true
+  #               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" || true
+  #               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" || true
+  #             else
+  #               echo "Stack is the latest"
+  #             fi
             
 
 workflows:
@@ -471,7 +471,7 @@ workflows:
           requires: [run-migrations]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
